# Generated by Django 3.0.7 on 2020-06-23 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poast_type', models.CharField(choices=[('b', 'Boast'), ('r', 'Roast')], default='b', max_length=10)),
                ('content', models.CharField(max_length=280)),
                ('up_vote', models.IntegerField(default=0)),
                ('down_vote', models.IntegerField(default=0)),
                ('sub_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('hidden_key', models.CharField(max_length=6)),
            ],
        ),
    ]
