# Generated by Django 3.0.7 on 2020-06-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0002_auto_20200623_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hidden_key',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
