# Generated by Django 3.0.7 on 2020-06-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0003_auto_20200623_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('b', 'Boast'), ('r', 'Roast')], default='b', max_length=10),
        ),
    ]
